name: Build GUI_Generic_ESP32 Manual

# Workflow może być uruchomiony ręcznie i automatycznie przy pushu lub pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # To pozwala na ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pobiera repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalacja środowiska PlatformIO
      - name: Set up PlatformIO
        run: |
          python3 -m pip install --upgrade platformio

      # Kompilacja projektu GUI_Generic_ESP32
      - name: Build Project for GUI_Generic_ESP32
        run: |
          platformio run -e GUI_Generic_ESP32

      # (Opcjonalnie) Uruchomienie testów
      - name: Run Tests
        run: |
          platformio test -e GUI_Generic_ESP32
