name: Build GUI_Generic_ESP32 Automat

# Workflow uruchamiany przy pushu lub pull request do gałęzi main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pobiera repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalacja środowiska PlatformIO
      - name: Set up PlatformIO
        run: |
          python3 -m pip install --upgrade platformio

      # Kompilacja projektu GUI_Generic_ESP32
      - name: Build Project for GUI_Generic_ESP32
        run: |
          platformio run -e GUI_Generic_ESP32

      # (Opcjonalnie) Uruchomienie testów
      - name: Run Tests
        run: |
          platformio test -e GUI_Generic_ESP32
